set(_CATKIN_CURRENT_PACKAGE "speech_recognition")
set(speech_recognition_VERSION "0.0.0")
set(speech_recognition_MAINTAINER "alex <alex@todo.todo>")
set(speech_recognition_PACKAGE_FORMAT "1")
set(speech_recognition_BUILD_DEPENDS "message_generation" "roscpp" "rospy" "std_msgs" "std_srvs")
set(speech_recognition_BUILD_EXPORT_DEPENDS "roscpp" "rospy" "std_msgs" "std_srvs")
set(speech_recognition_BUILDTOOL_DEPENDS "catkin")
set(speech_recognition_BUILDTOOL_EXPORT_DEPENDS )
set(speech_recognition_EXEC_DEPENDS "roscpp" "rospy" "std_msgs" "std_srvs")
set(speech_recognition_RUN_DEPENDS "roscpp" "rospy" "std_msgs" "std_srvs")
set(speech_recognition_TEST_DEPENDS )
set(speech_recognition_DOC_DEPENDS )
set(speech_recognition_URL_WEBSITE "")
set(speech_recognition_URL_BUGTRACKER "")
set(speech_recognition_URL_REPOSITORY "")
set(speech_recognition_DEPRECATED "")